Merging develop into master (#38)
* Feature/sd-10 (#2)

* Created an initial server setup

It is the basic server with routing and static serving.
Includes structures for different modules.

SD-10

* Fixed the bug with README.md

Fixed coding format of README.md

SD-10

* Fixed the coding formating of readme.md

Fixed the coding formating of readme.md.

sd-10

* Updated npm dependencies

added cookie session to dependencies of npm

sd-10

* Updated the path to apidocs

Updated the path to apidocs.

sd-10

* Fixed the bug with apis

Fixed the bug with apis

sd-10

* fixed api

sd-19

* Added user and event API routing.

* Engine outline and geo library implementation.

* Deleted old file.

* Added user and event API routing. (#4)

* Added Mongoose models and wrappers (#3)

Added mongoose models wrappers to have basic
interaction with the. Wrote test for them.

sd-10

* yelp api wapper

* Yelp API wapper

* New user creation finished

* Finished route to get all users

* Wrote handler for getting a specific user by their facebook id

* Finished handler for updating a user

* Fixed bug in geolib. Added comments explaining code.

* Add Yelp Api wrapper

Added yelp API wrapper.

sd-15

* Trying to get yelp calls to work

* Feature/sd 15 (#7)

* Engine outline and geo library implementation.

* Deleted old file.

* yelp api wapper

* Yelp API wapper

* Add Yelp Api wrapper

Added yelp API wrapper.

sd-15

* Changes to both event and user APIs. Came across some issues with changing documentation. Considering using an API documentation tool called Apiary

* Almost finished with API, as far as I know

* Changed accesstokenfrom request body to query.

- Added a middleware route that filters all incoming API calls for an
  accesstoken
- Changed User and Event routing to check query for accesstoken instead of
  request body

query-token-update

* Moved middleware filter to middleware directory

Made requested changes

query-token-update

* Changed the DB schema to match Android models

- When a User is returned from Mongo, the __v field is hidden
- Created virtual functions that generate starttimeLong and createtimeLong
  fields
- Also deleted an unused variable in user-routing

query-token-update

* Changed access token from request body to query. (#8)

* Changed accesstokenfrom request body to query.

- Added a middleware route that filters all incoming API calls for an
  accesstoken, Made requested changes
- Changed User and Event routing to check query for accesstoken instead of
  request body

* Moved tests and cleaned up engine.

* Fixed the create event Handler (#11)

Create event handler now stores
the information such as title and description

hotfix/create-event

* Added docker files. It works locally, but will test on the server (#13)

* Update app.js

* Adding user population to attendees and invitations fields on event get call

* Fixed the bug with creating event (#12)

The invitations are stored in the db now.

* Feature/sd 15 (#15)

* Added user and event API routing.

* Feature/sd 15 (#7)

* Engine outline and geo library implementation.

* Deleted old file.

* yelp api wapper

* Yelp API wapper

* Add Yelp Api wrapper

Added yelp API wrapper.

sd-15

* Added docker files. It works locally, but will test on the server (#13)

* wrapper of server side fcm api calls

* Updating event routing to populate user fields

* Notifications are now being sent when a user is invited to an event

* Modified the api responce (#16)

Modified the API response for getUserEventHandler
to that it will populate the admin with selected
fields

sd-20

* Firebase token now changes when the user uninstalls then reinstalls the app

* FCM sends data now instead of notification

* Fixed the bug with inviting

const was deprecated

* Changed UserSchema location to be numbers instead of strings

* Updating documentation and changing a few of the api paths. Now can update user location in the update user API call as well as when an event invitation is accepted

* Updated API for responding to Invitation (#18)

Responce doesn't include invitation, admin, attendees.
The FCM data has been updated.
The runTest for server engine has been disabled

* Feature/timeout (#19)

* Starting the event timeout that triggers the decision engine. Currently prints out the resulting Yelp place

* Adding yelp results to event database, notifying people subscribed to the event's topic

* Storing recent location of user when he creates an event

* Changing decision made fcm message to send to user registration tokens instead of a topic

* Removed console log debug

* Update database-event.test.js

* Hotfix/user response bug (#20)

* Fixed the bug with api

* Got rid of console.log

* Fixed bug when users had undefined location coordinates

* HTTPS setup

* Updated gitignore to ignore npmlog

* Making middleware actually do something (#21)

* Api testing (#22)

* Fixed existing tests

* Adding config files and removing http connection to the server

* Added the Yelp data to DECISION notifcation

- Added Yelp information fields to notification
- DECISION notification now being sent to everyone who accepted

hotfix/decision/notification

* Update server-route.js

* Update event-timer.js

* Add lockInEventHandler

* Update event-routing.js

* Update event-routing.js

* Add exports

* Server now sends the admin's fbtokenid on invite

This will allow the Android side to get the admin's
profile pic for notifications

origin/develop

* Started random event name generation.

* Changed the wordnik-bb to my own repository.

* Implemented reroll function for engine. (#27)

* Switching server to use Google Places API (#28)

* Reroll API implemented (#29)

* Debugging TypeError: $.Deferred is not a function

* Fixed the compilation bug.

* Random event naming.

* Putting event name generation in its own module because it doesn't fit with the engine

* Random event naming implementation (#32)

* Implemented random event naming on undefined title input or empty string input

* Getting rid of extra console logs

* Reverse event list and only return last 24 hours of events (#34)

* Only returns events within the last 24 hours

* Reversed order of events returned. Kind of messy. Couldn't figure out how to do it natively with Mongoose so I just used the javascript array reverse function

* Added the website

* Remove swagger and yelp (#36)

* Made it so that the get all users and get all events API calls can only be used when NODE_ENV environment variable is 'dev' (#37)

* Site changes that I'm assuming are finished